version: "3.8"
services:
  roon-server:
    image: ez2raven/roon-server:latest
    container_name: roon-server
    network_mode: "host"
    restart: always    
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      - TZ="Asia/Singapore"
    volumes:
      - ./roon-app:/app
      - ./roon-data:/data
      - ./roon-music:/music
      - ./roon-backups:/backup
volumes:
  roon-app:
  roon-data:
  roon-backups:
  roon-music: